
#ifndef LIB_RUBIKS_CORE_INTERNAL_GCC_ATTRIBUTES_HEADER
#define LIB_RUBIKS_CORE_INTERNAL_GCC_ATTRIBUTES_HEADER


#define RBC_API __attribute__((visibility("default")))


#endif /* LIB_RUBIKS_CORE_INTERNAL_GCC_ATTRIBUTES_HEADER */
