
#ifndef LIB_RUBIKS_CORE_INTERNAL_MINGW_ATTRIBUTES_HEADER
#define LIB_RUBIKS_CORE_INTERNAL_MINGW_ATTRIBUTES_HEADER


#error "RUBIKS_API attribute not implemented for MinGW"


#endif /* LIB_RUBIKS_CORE_MINGW_ATTRIBUTES_HEADER */
