
#ifndef LIB_RUBIKS_CORE_INTERNAL_MSVC_ATTRIBUTES_HEADER
#define LIB_RUBIKS_CORE_INTERNAL_MSVC_ATTRIBUTES_HEADER


#define RBC_API __declspec(dllexport)


#endif /* LIB_RUBIKS_CORE_INTERNAL_MSVC_ATTRIBUTES_HEADER */
