
#ifndef LIB_RUBIKS_CORE_INTERNAL_MSVC_ATTRIBUTES_HEADER
#define LIB_RUBIKS_CORE_INTERNAL_MSVC_ATTRIBUTES_HEADER


#error "RUBIKS_API attribute not implemented for MSVC"


#endif /* LIB_RUBIKS_CORE_INTERNAL_MSVC_ATTRIBUTES_HEADER */
